"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const menuController_1 = require("../controllers/menuController");
const validate_1 = require("../middleware/validate");
const menuSchema_1 = require("../schemas/menuSchema");
const router = (0, express_1.Router)();
router.get("/", menuController_1.getAllMenuItems);
router.get("/:id", menuController_1.getMenuItemById);
router.post("/", (0, validate_1.validate)(menuSchema_1.menuItemSchema), menuController_1.createMenuItem);
router.put("/:id", (0, validate_1.validate)(menuSchema_1.menuItemSchema.partial()), menuController_1.updateMenuItem);
router.delete("/:id", menuController_1.deleteMenuItem);
exports.default = router;
