"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const orderController_1 = require("../controllers/orderController");
const validate_1 = require("../middleware/validate");
const orderSchema_1 = require("../schemas/orderSchema");
const orderController_2 = require("../controllers/orderController");
const orderController_3 = require("../controllers/orderController");
const router = (0, express_1.Router)();
router.post("/", (0, validate_1.validate)(orderSchema_1.orderSchema), orderController_1.createOrder);
router.get("/", orderController_2.getOrders);
router.put("/:id", (0, validate_1.validate)(orderSchema_1.orderSchema.partial()), orderController_3.updateOrder);
exports.default = router;
